DROP TABLE IF EXISTS accounts CASCADE;

CREATE TABLE accounts (
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL,
  main_password VARCHAR(255) NOT NULL,
  created TIMESTAMP NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE
);
